---
# a playbook to create the necessary users, groups and
# sudoer settings needed for ansible to manage a node.
- hosts: all
  strategy: free
# this used to be set to ubuntu but the {{ cm_user }} is the only
# user that gets created during kickstart
  vars:
    ansible_ssh_user: "{{ cm_user }}"
  roles:
    - ansible-managed
  become: true
