---
- name: Purge resolvconf
  apt:
    name: resolvconf
    state: absent
    purge: yes
  when: ansible_pkg_mgr == "apt"

- name: Ensure lab_domain is in search domains in /etc/resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^search .*"
    line: "search {{ lab_domain }}"

- name: Ensure domain is set in /etc/resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^domain .*"
    line: "domain {{ lab_domain }}"
